apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: default
  labels:
    app: gitops-app
spec:
  selector:
    matchLabels:
      app: gitops-app
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: aman21xo/gitops-app:1.0.2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: gitops-app
      restartPolicy: Always
