apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: default
spec:
  selector:
    app: gitops-app
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
